server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader:
            true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      group-id: rv_relai2